bisdn/meta-bisdn-linux

recipes-extended/baseboxd/baseboxd_1.9.17.bb
=> baseboxd: update to 1.9.17

recipes-extended/baseboxd/baseboxd_1.9.18.bb
=> baseboxd: update to 1.9.18

conf/distro/bisdn-linux.conf
=> distro: bump version to 4.1.0

conf/distro/bisdn-linux.conf
=> distro: bump version to 4.2.0

recipes-extended/baseboxd/baseboxd_1.9.20.bb
=> baseboxd: bump version to 1.9.20

recipes-extended/baseboxd/baseboxd_1.9.23.bb
=> baseboxd: update to 1.9.23

recipes-extended/baseboxd/baseboxd_1.9.24.bb
=> baseboxd: bump version to 1.9.24

recipes-kernel/linux/linux-yocto-onl_5.15.bbappend
=> linux: enable our kernel config for 5.15 as well

recipes-extended/baseboxd/baseboxd_1.9.25.bb
=> baseboxd: bump version to 1.9.25

conf/distro/bisdn-linux.conf
=> distro: bump version to 4.4.0

recipes-core/images/full.bb
=> full: add git to image

conf/distro/bisdn-linux.conf
=> distro: bump version to 4.3.1

recipes-extended/baseboxd/baseboxd_1.9.26.bb
=> baseboxd: bump version to 1.9.26

recipes-extended/baseboxd/baseboxd_1.9.27.bb
=> baseboxd: bump version to 1.9.27

recipes-extended/baseboxd/baseboxd_1.9.28.bb
=> baseboxd: bump version to 1.9.28

conf/distro/bisdn-linux.conf
In preparation for the upcoming stability release, bump the minor
version.
=> distro: bump version to 4.4.1

recipes-extended/baseboxd/baseboxd_1.9.29.bb
=> baseboxd: Bump version to 1.9.29

recipes-extended/baseboxd/baseboxd_1.10.0.bb
=> baseboxd: bump version to 1.10.0

recipes-extended/baseboxd/baseboxd_1.10.2.bb
=> baseboxd: bump version to 1.10.2

recipes-extended/baseboxd/baseboxd_1.10.3.bb
=> baseboxd: Bump version to 1.10.3

recipes-extended/baseboxd/baseboxd_1.10.5.bb
=> baseboxd: Bump version to 1.10.5

recipes-extended/baseboxd/baseboxd_1.11.0.bb
=> baseboxd: Bump version to 1.11.0

recipes-extended/baseboxd/baseboxd_1.11.1.bb
=> baseboxd: bump version to 1.11.1

conf/distro/bisdn-linux.conf
=> distro: bump version to 4.5.0

conf/distro/bisdn-linux.conf
Signed-off-by: hilmar.magnusson <hilmar.magnusson@bisdn.de>
=> distro: bump version to 4.6.0

recipes-extended/baseboxd/baseboxd_1.11.3.bb, recipes-extended/baseboxd/baseboxd_1.11.4.bb
=> baseboxd: Bump version to 1.11.4

recipes-support/rofl-ofdpa/rofl-ofdpa_2.0.4.bb
=> rofl-ofdpa: Bump version to 2.0.4

conf/distro/bisdn-linux.conf
Signed-off-by: Hilmar Magnusson <hilmar.magnusson@bisdn.de>
=> distro: bump version to 4.6.1

recipes-extended/baseboxd/baseboxd_1.11.5.bb
=> baseboxd: Bump version to 1.11.5

recipes-extended/baseboxd/baseboxd_1.11.6.bb
=> baseboxd: Bump version to 1.11.6

recipes-extended/baseboxd/baseboxd_1.11.8.bb
=> baseboxd: Bump version to 1.11.8

conf/distro/bisdn-linux.conf
=> bump distro to version 3.7.0

recipes-extended/baseboxd/baseboxd_1.12.1.bb
=> baseboxd: Bump version to 1.12.1

conf/distro/bisdn-linux.conf
=> bump distro to version 4.8.0

recipes-extended/baseboxd/baseboxd_1.12.2.bb
=> baseboxd: Bump version to 1.12.2

conf/distro/bisdn-linux.conf
=> bump distro to version 4.8.1

conf/distro/bisdn-linux.conf
=> bump distro version to 4.8.2

recipes-extended/baseboxd/baseboxd_1.12.5.bb
=> baseboxd: Bump version to 1.12.5

conf/distro/bisdn-linux.conf
=> bump distro version to 4.8.3

recipes-extended/baseboxd/baseboxd.inc
Default branch is now main, so update SRC_URI accordingly.
=> baseboxd: change branch from master to main

recipes-support/rofl-common/rofl-common.inc, recipes-support/rofl-ofdpa/rofl-ofdpa.inc
master is now main, so update the recipes.
=> rofl-*: update branch from master to main

conf/distro/bisdn-linux.conf
In preparation of the next bug fix release, bump the patch version.
=> distro: bump version to 5.0.1

conf/distro/bisdn-linux.conf
In preparation of the next release, bump the version.
=> distro: bump version to 5.1.0

conf/distro/bisdn-linux.conf
In preparation of a maintenance release, bump the patch version.
=> distro: bump version to 5.1.1

conf/distro/bisdn-linux.conf
we have enough changes to warrant a minor version bump, so do that.
=> distro: bump version to 5.2.0

recipes-extended/baseboxd/baseboxd.inc, recipes-extended/baseboxd/baseboxd_2.0.15.bb
Switch the source branch to 2.0.x and update baseboxd to 2.0.15.
=> v5.1.x: baseboxd: update to 2.0.15

conf/distro/bisdn-linux.conf
now that 5.1.1 is released, bump the version to indicate that this isn't 5.1.1 anymore.
=> distro: bump version to 5.1.2

conf/distro/bisdn-linux.conf
Next BISDN Linux 4.x version is 4.9.0
=> distro: bump version to 4.9.0

recipes-support/mstpd/mstpd_0.1.0.bb
Update mstpd to latest for v4.x as well, to have all existing fixes in it.
=> v4.x: update mstpd to 0.1.0+bisdn6

recipes-extended/man-pages/man-pages_%.bbappend
This change installs the man page for switch_tcpdump into the image.
=> Install switch_tcpdump man page

recipes-extended/baseboxd/baseboxd_1.12.6.bb, recipes-extended/baseboxd/baseboxd_1.12.7.bb
Update baseboxd to latest 1.12 release 1.12.7.
=> v4.x: baseboxd: update to 1.12.7

conf/distro/bisdn-linux.conf, files/group, files/passwd, recipes-core/systemd/systemd.inc, recipes-devtools/run-preinsts/run-preinsts/run-preinsts.service
Backport of PRs #262, #263 and #272.
=> v4.x: distro: enable static group ids and user ids

conf/distro/bisdn-linux.conf
Bump version from the broken 5.3 to 5.3.1.
=> conf: distro: bump version to 5.3.1

recipes-extended/baseboxd/baseboxd_2.4.3.bb
Update baseboxd to 2.4.3:
```
909fca6630b0 Bump version to 2.4.3
cab327f45add nl_vlan: simplify ::get_vid()
```
=> baseboxd: update to 2.4.3

conf/distro/bisdn-linux.conf
Next version will be a feature release, so bump the minor version.
=> distro: bump version to 5.4.0

recipes-extended/baseboxd/baseboxd_2.4.4.bb
Update baseboxd to 2.4.4:
```
4d87783ae9d0 Bump version to 2.4.4
ec6dbeaaf0a4 cnetlink: also remove routes on VRF changes
11577be53043 nl_l3: check table as well for link local route checking
```
=> baseboxd: update to 2.4.4

recipes-extended/baseboxd/baseboxd_2.5.0.bb
Update baseboxd to 2.5.0:
```
5c915dd07284 Bump version to 2.5.0
6d13c4e6533f Merge pull request #450 from bisdn/jogo_set_rx_rate
17be6f3e8ec5 set rx rate to unlimited for knet
82d1fc862084 proto: update to latest HEAD
```
=> baseboxd: update to 2.5.0

conf/distro/bisdn-linux.conf
Since we added features, bump the version to 2.5.0.
=> distro: bump version to 2.5.0
