bisdn/meta-bisdn-linux

recipes-core/base-files/base-files/30-disable-ipv6-auto-addr-gen.conf, recipes-core/base-files/base-files_%.bbappend, recipes-protocols/frr/clippy-native_8.0.1.bb, recipes-protocols/frr/frr_8.0.1.bb
The upstream FRR project changed functionality in the release 8.0.1 by
now requiring IPv6 link local addresses on all interfaces (following
rfc4291). To still allow ipv6 routing by default, we should also follow
this rfc and not disable IPv6 ll addressing.
=> update frr to 8.0.1 and enable ipv6ll by default

recipes-core/systemd/files/99-enp.network, recipes-core/systemd/systemd.inc
The switch from Yocto warrior to Yocto dunfell brought in a default
wired config wired.network, [link to repo](http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-core/systemd/systemd-conf/wired.network?h=dunfell), which configures
DHCP on all interfaces starting with eth and en. Since 80 is lower number
than 99, it matches first, and thus always takes precedence before our
99-enp.network, preventing any intended management interface config
from being applied.
Removing the file we package with systemd removes the duplicated
configuration to allow the pre-packaged file taking precendence and applying
the DHCP configuration.
Fixes #13 
=> systemd: drop redundant management interface configuration file

recipes-devtools/python/python3_%.bbappend
Ccache will leak into python's sysdata module, and any attempt to build
modules locally will attemp to build with ccache.
Since we do not ship a ccache package by default, make sure we do not
build python with ccache so building modules works with provided
packages.
=> python3: disable ccache use

conf/distro/bisdn-linux.conf
Set the FEEDDOMAIN and FEEDURIPREFIX to what is used for nightly builds.
This allows up using these in the SRC_URI of binary only packages, and
then only need to update/override these for releases instead of updating
the SRC_URI in the recipes.
=> distro: update feed defaults to actual nightly location

recipes-core/images/full.bb
Add a default locale of en-us to images, as e.g. tmux requires it.
Without any locales installed, tmux will fail with:
tmux: need UTF-8 locale (LC_TYPE), but have ANSI_X3.4-1968
=> images: full: include en-us locale

recipes-devtools/python/python3-oslo.config_git.bb, recipes-devtools/python/python3-ryu_git.bb, recipes-extended/baseboxd/baseboxd.inc, recipes-support/rofl-common/rofl-common.inc, recipes-support/rofl-ofdpa/rofl-ofdpa.inc
Github just turned off the git transport on their servers, and checking
out now fails with:
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
So switch to https to make stuff build again.
=> treewide: switch git transport to https for github

recipes-extended/iptables/iptables/ip6tables.service
There is a lock on xtables when the service starts, so the service
fails. Adding the waiting (-w) parameter when executing will let the
service wait for the lock to be removed.
Signed-off-by: Hilmar Magnusson <hilmar.magnusson@bisdn.de>
=> ip6tables: add -w parameter to solve xtables lock

recipes-core/images/full.bb
Rsync is much faster than the alternatives, especially when copying
multiple files multiple times.
We don't have a good option for copying test files to (and updating them
on) BISDN Linux.
- scp -r transfers every file whether it is already in the desired state
or not
- The Ansible copy module is notorious for being inefficient and slow,
even compared to scp. The recommended alternative is the Ansible
synchronize module which is just a wrapper around rsync.
Adding rsync increases the image size by 250 KB.
Signed-off-by: Roger Luethi <roger.luethi@bisdn.de>
=> images/full: add rsync

recipes-devtools/python/python3-ryu/0001-pcaplib.py-add-option-to-flush-each-packet.patch, recipes-devtools/python/python3-ryu_git.bb
When using the pcap writer, packets may take a long time to appear in
the file simply because the write buffer is not full yet. This can be
quite annoying in test environments where traffic is very low.
This commit addresses the issue by adding an option to ensure that
packets are written to the pcap file immediately. The option is turned
off by default.
Signed-off-by: Roger Luethi <roger.luethi@bisdn.de>
=> ryu: pcaplib.py: add option to flush each packet

recipes-core/systemd/files/20-network-io.conf
net.core.rmem_max is lower than the rmem_default value, and thus will lead to
loss when baseboxd reads netlink messages, because baseboxd uses the max value
to set its buffer size. Set the rmem_max value to the same as the
wmem_max value.
This should solve [baseboxd issue 376](https://github.com/bisdn/basebox/issues/376)
=> Set max read buffer size

recipes-support/libnl/libnl_3.5.0.bb
Libnl seems to have moved from master to main, with replacing master
with a very old revision(?). So point to main to make it build again.
Fixes the following error:
```
WARNING: libnl-1_3.5.0-r4 do_fetch: Failed to fetch URL git://github.com/thom311/libnl.git;protocol=https, attempting MIRRORS if available
ERROR: libnl-1_3.5.0-r4 do_fetch: Fetcher failure: Unable to find revision 7b167ef85f6eb4d7faca349302478b2dc121e309 in branch master even from upstream
ERROR: libnl-1_3.5.0-r4 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/thom311/libnl.git;protocol=https')
ERROR: Logfile of failure stored in: /tmp/master/work/cortexa9-vfp-poky-linux-gnueabi/libnl/1_3.5.0-r4/temp/log.do_fetch.45463
ERROR: Task …
```
=> libnl: switch to main branch to fix build

recipes-devtools/grpc/grpc_1.24.3.bbappend
Googletest renamed their default branch from master to main, so we need
to update our source definition, else the checkout will fail.
No functional changes, so no PR bump needed.
=> grpc: fix checkout by updating googletest branch to main

recipes-extended/baseboxd/baseboxd.inc, recipes-protocols/frr/frr.inc, recipes-support/libnl/libnl_3.5.0.bb, recipes-support/mstpd/mstpd_git.bb, recipes-support/rofl-common/rofl-common.inc, recipes-support/rofl-ofdpa/rofl-ofdpa.inc
Update all of our recipes to use the correct, current SPDX license identifiers, based on https://spdx.org/licenses/ (Version: 3.16 2022-02-06).
Mostly FOOvX => FOO-X and GPL-2.0 refined into 2.0-only or 2.0-or-later.
Packages imported from upstream were intentionally left untouched.
=> update LICENSE to current SPDX identifiers

recipes-support/mstpd/mstpd_git.bb
=> bump mstpd version to 0.1.0+bisdn2 (dropped python2 for debian build)

recipes-extended/baseboxd-tools/baseboxd-tools/bundle-debug-info
Like "bridge mdb", "bridge -d vlan" needs the bridge module to be present. Otherwise, the command will return an error:
`RTNETLINK answers: Operation not supported`
=> baseboxd-tools: bundle-debug-info: handle missing bridge module

recipes-core/images/minimal.bb
OpenSSH 9.0 defaults to the SFTP protocol even when using the scp
binary, unless explicitly told to use SCP via an option.
Since we are not strapped for space, let's just add the appropriate
sftp-server package to the image (and client as well) to allow seamless
upgrades of OpenSSH to 9.0+ on host systems.
=> images/minimal: add sftp and sftp-server

recipes-devtools/python/python3-ryu_git.bb, recipes-extended/baseboxd/baseboxd.inc, recipes-support/libyang/libyang2_2.0.7.bb, recipes-support/rofl-common/rofl-common.inc, recipes-support/rofl-ofdpa/rofl-ofdpa.inc
There is a move from master to main for the default branch in git repos,
so the assumption that no branch set means master is less and less true.
Newer bitbake versions warn about the absence of a branch, and likely
will eventually fail if none is set, so set it explicitly to master.
=> always set a branch for git source repos

recipes-core/basebox-user/basebox-user.bb
Supplying a plain-text password is a yocto-proprietary extension that
got removed in later releases. So switch to supplying a pregenerated
hashed password with the standard option -p.
While we could generate the password hash dynamically, this would break
reproducability.
=> basebox-user: use pre-computed password hash

recipes-core/base-files/base-files/system-backup.txt
We need to make sure that we take over /etc/gshadow as well, else
/etc/groups and /etc/gshadow might get out of sync.
Fixes: c37e24ae5fde ("base-files: add default backup file lists")
=> base-files: backup /etc/gshadow as well

recipes-core/images/onie-nos-installer.inc
Instead of requiring machines to set the BISDN_ONIE_PLATFORM, calculate
it ourselves by taking ONIE_PLATFORM and replacing all underscores with
dashes.
=> onie-nos-installer: calculate BISDN_ONIE_PLATFORM

recipes-core/basebox-user/basebox-user.bb
While the string makes it fine into the script for generating the
password, the single quotes still not prevent the $ from being
interpreted, so escape them to make sure the hash is correctly set.
Fixes: 4f2ed35fa0e8 ("basebox-user: use pre-computed password hash")
=> basebox-user: fix password generation

recipes-support/libyang/libyang2_2.0.194.bb
Newer Yocto versions won't provide pkg-config by default, so we need to
make sure that we inherit the appropriate class.
Without it, libyang2 will not have a the pkg-config available, and will
not generate a libyang.pc.
This will then cause depending packages like frr to fail detect
libyang2:
```
| checking for LIBYANG (libyang >= 2.0.0)... no
| configure: error: libyang (>= 2.0.0) was not found on your system.
| NOTE: The following config.log files may provide further information.
| NOTE: /tmp/kirkstone/work/cortexa9-vfp-poky-linux-gnueabi/frr/8.2.2-r0/build/config.log
| ERROR: configure failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/ubuntu/bisdn-linux/kirkstone/poky/meta-switch/recipes-protocols/frr/frr_8.2.2.bb:do_configure) failed with exit code '1'
```
From …
=> libyang2: explicitly enable pkg-config

recipes-support/mstpd/mstpd_git.bb
Update to 0.1.0+bisdn3:
* b2cb344b5f4d release: update for 0.1.0+bisdn3
* 57f87d5f487d brmon: do not use the monitor socket for getting the vlan table
=> mstpd: update to 0.1.0+bisdn3

recipes-protocols/frr/clippy-native_8.3.bb, recipes-protocols/frr/files/support_bundle_commands.conf, recipes-protocols/frr/frr_8.3.bb
* update to frr 8.3
* apply upstream changes to our support_bundle_commands.conf
New features:
*  Notification Message support for BGP Graceful Restart
(http://docs.frrouting.org/en/latest/bgp.html#clicmd-bgp-graceful-restart-notification)
*  BGP Cease Notification Subcode For BFD
Send Hold Timer for BGP
*  RFC5424 syslog support
(http://docs.frrouting.org/en/latest/extlog.html?#clicmd-destination-syslog-supports-rfc5424)
*  PIM passive command
(http://docs.frrouting.org/en/latest/pim.html#clicmd-ip-pim-passive)
Detailed changelog:
* https://github.com/FRRouting/frr/releases/tag/frr-8.3
=> frr: update to 8.3

recipes-extended/baseboxd/baseboxd_1.12.0.bb
Update baseboxd to 1.12.0:
8fd7d56bfa28 Bump version to 1.12.0
7bebed71f50f Merge pull request #387 from bisdn/jogo_use_mac_from_of
5bba6f5ec1e3 tap_manager: set MAC address on created interfaces
1c0028399755 knet_manager: set MAC address of created interfaces
de9870de97b0 nbi: pass MAC address to port manager
752cf5edff68 of-dpa: add MAC address to port notification
6cdeac564f8b Merge pull request #386 from bisdn/rl_update_clang_format
c2c3169a8876 linter.yml: disable failing linters
cbac1dfd4b55 linter.yml: use slim linter image
a89bbf9876f4 linter.yml: change default branch from main to master
12e6449172aa Copy linter.yml template to enable nable super-linter
443a6ae726b0 Update source files for clang-format
=> baseboxd: bump to 1.12.0

recipes-core/systemd/files/10-any_interface_is_enough.conf, recipes-core/systemd/systemd.inc
The docker service (and all other services depending on
systemd-networkd-wait-online) take 2 extra minutes to start because it
takes that long for the service waiting for all interfaces to come up to
time out.
Instead of waiting for all interfaces to come up, wait for any interface
(i.e., the management interface) to come up.
=> systemd: let any interface satisfy systemd-networkd-wait-online

recipes-protocols/frr/clippy-native_8.2.2.bb, recipes-protocols/frr/files/support_bundle_commands.conf, recipes-protocols/frr/frr_8.2.2.bb
* at the time of writing, frr 8.3 seems to be a lot more unstable than
frr 8.2.2, so we are sticking with the older release for now
This reverts commit 651854ccab17f6227329c524137305f6062510ee.
=> Revert "frr: update to 8.3"

recipes-core/base-files/base-files_%.bbappend, scripts/installer/install.sh
Set the default hostname based on the ONIE machine name at install time
instead of hardcoded based on yocto machine name.
This makes sure that the default hostname matches the machine the image
is installed on, in case the image supports multiple machines.
This has a few side effects:
accton-as4610 will now use accton-as4610-30 or accton-as4610-54, based on
which kind it is installed on.
agema-ag5648 and agema-ag7648 will use delta-ag5648 resp. delta-ag7648,
since ONIE calls itself delta and not agema.
=> set default hostname based on ONIE machine name

recipes-extended/baseboxd-tools/baseboxd-tools/bundle-debug-info
The techsupport/switch call may take several minutes, and blocks OF-DPA
while doing so. This can break the openflow connection, especially on
AS4610.
Since this can cause unexpected side effects, split it out into its own debug
target, and do not collect it by default.
=> baseboxd-tools: collect-debug-info: do not call techsupport by default

recipes-extended/sudo/sudo_%.bbappend
To allow reverting to a pre 4.7.0 image after installing 4.8.0, restore
the old include syntax which is understood by older sudos.
=> sudo: revert to old syntax for backward compatibility

recipes-core/systemd/files/wired.network, recipes-core/systemd/systemd-conf_%.bbappend
Some network drivers need to set the link (temporarily) down to apply a
new MTU. This can cause systemd-networkd to regard the link as down, and
restart the whole process.
This affects e.g. the intel embedded NICs found in many switches.
Fix this by ignoring short link losses. See
https://github.com/systemd/systemd/issues/18738
for details.
=> systemd-conf: avoid link flapping when DHCP sets MTU

recipes-core/images/minimal.bb
grub is only needed for x86-64 so only add it to the image if we are
building for it.
=> minimal: install grub only for x86-64 targets

recipes-core/images/onie-nos-installer.inc, scripts/installer/install.sh, scripts/installer/machine/arm-accton_as4610_30-r0/platform.conf, scripts/installer/u-boot-arch/install.sh, scripts/installer/x86_64/install.sh
This PR cleans up some of the variable and function names used in the installer code. In particular, it disambiguates names that have different meanings in different contexts. It also drops variables that don't appear to be useful (anymore).
=> installer: clean up names

recipes-extended/baseboxd/baseboxd_1.12.3.bb
Update baseboxd to 1.12.3:
0aa8875748d3 bump version to 1.12.3
6d5f491fab2d nl_bridge: default STP state should be forwarding
=> baseboxd: update to 1.12.3

recipes-support/mstpd/mstpd_git.bb
Update to 0.1.0+bisdn4:
* 79402ba4763c release: update for 0.1.0+bisdn4
* 610f94f98e86 bridge_track: only set ports to forwarding when the bridge is up
=> mstpd: update to 0.1.0+bisdn4

recipes-extended/baseboxd/baseboxd_1.12.4.bb
Update baseboxd to 1.12.4:
* cnetlink: fix handling of bond mode changes
=> baseboxd: update to 1.12.4

scripts/installer/machine/arm-accton_as4610_30-r0/platform.conf
The ONL installer will force the partition table to msdos despite ONIE saying gpt in its EEPROM. This breaks various assumptions, including ONIE's uninstall scripts, which then fail to remove anything.
To work around this erase the disk and install a fresh partition table if we encounter this.
=> installer: accton-as4610: handle wrong partition table type

recipes-protocols/frr/files/CVE-2022-37032.patch, recipes-protocols/frr/files/CVE-2022-37035.patch, recipes-protocols/frr/frr.inc, recipes-protocols/frr/frr_8.2.2.bb
Import fixes for CVEs CVE-2022-37032 and CVE-2022-37035 from meta-openembedded.
=> frr: fix CVE-2022-37032, CVE-2022-37035

scripts/installer/install.sh, scripts/installer/machine/arm-accton_as4610_30-r0/platform.conf, scripts/installer/machine/x86_64-accton_as4630_54pe-r0/platform.conf
Allow supporting multiple switch models with the need to (not) rename the management port by letting the installer create the appropriate `90-enp.link` file at installation time, and then add the appropriate value to as4610 and as4630-54{p,t}e.
=> installer: setup management port

recipes-extended/onie-tools/onie-tools/onie-bisdn-rescue, recipes-extended/onie-tools/onie-tools/onie-bisdn-uninstall, recipes-extended/onie-tools/onie-tools/onie-bisdn-upgrade
The utilities need root privileges, so we should make sure we have them before attempting anything, else we just print confusing error messages.
Fixes #124.
=> onie-tools: check for root before doing things

recipes-kernel/linux/linux-yocto-onl_5.10.bbappend, recipes-kernel/linux/linux-yocto-onl_5.15.bbappend, recipes-kernel/linux/linux-yocto-onl_5.4.bbappend, recipes-kernel/linux/linux-yocto-onl_bisdn_linux.inc
Drop the single KERNEL_FEATURE enabled via bbappend, since we now enable it in linux-yocto-onl directly.
Depends on https://github.com/bisdn/meta-open-network-linux/pull/95
=> drop the linux-yocto-onl bbappend

scripts/installer/install.sh, scripts/installer/machine/arm-accton_as4610_30-r0/platform.conf
Instead of requiring a populated fw_env.config in the image, create one
during install time based on the platform config.
=> installer: create fw_env.config during installation

conf/distro/bisdn-linux.conf
meta-virtualization enabled the seccomp feature for docker-ce with 51833d0e1311 ("docker: add seccomp to default packageconfig settings"), but we do not have seccomp enabled in our builds, breaking it due to inresolved dependencies.
To restore the old state, restore the packageconf to its previous state without seccomp.
Fixes the following build error:
ERROR: Nothing PROVIDES 'libseccomp' (but .../poky/meta-virtualization/recipes-containers/docker/docker-ce_git.bb DEPENDS on or otherwise requires it)
libseccomp was skipped: missing required distro feature 'seccomp' (not in DISTRO_FEATURES)
ERROR: Required build target 'docker-ce' has no buildable providers.
Missing or unbuildable dependency chain was: ['docker-ce', 'libseccomp']
=> distro: disable seccomp in docker-ce again

conf/distro/bisdn-linux.conf, recipes-core/systemd/files/10-disable-llmnr.conf, recipes-core/systemd/systemd.inc, recipes-extended/iptables/iptables/ip6tables.rules, recipes-extended/iptables/iptables/iptables.rules
Issue #130 highlights the issue of the control plane ports being accessible from the data ports by default.
This blocks all incoming TCP/UDP connections from the dataplane to management ports.
=> Remove NFS, disable LLMNR and block ports 5000, 6653 and 50051 from the data-plane

recipes-devtools/grpc/files/1.46.6/0001-CMakelists.txt-allow-building-the-grpc_cli-utility-o.patch, recipes-devtools/grpc/grpc_1.46.6.bbappend
meta-openembedded updated grpc to v1.46.6 with 06fb36d33cb3 ("grpc: upgrade 1.45.2 -> 1.46.6") to fix zlib CVE CVE-2022-37434, so we need to update our bbappend accordingly.
The googletest submodule was not updated between these versions, so only the patch needed a refresh.
=> grpc: update append for v1.46.6

recipes-core/base-files/base-files/system-backup.txt
i2c-ismt is expected to be autoprobed on releases 4.8.x and earlier, but
master has it blacklisted via /etc/modprobe.d/i2c-ismt.conf.
Since Yocto treats it as a configuration file, it gets backed up when
upgrading, which can break the system when going back from
master/nightly to a previous release.
To avoid this happening, explicitly drop the file from backups.
=> base-files: do not backup /etc/modprobe.d/i2c-ismt.conf

conf/distro/bisdn-linux.conf
Now that the default branch is main, the path where nightly builds appear will also change, so we need to update the FEEDURIPREFIX to point to the new location.
=> distro: update FEEDURIPREFIX from master to main

recipes-extended/baseboxd-tools/baseboxd-tools/bundle-debug-info
* to avoid getting a bunch of symlinks in the debug bundle, we should make sure to dereference them while taring
=> bundle-debug-info: dereference all symlinks while archiving

recipes-core/base-files/base-files/system-backup.txt
i2c-i801 is expected to be autoprobed on releases 4.8.x and earlier, but main has it blacklisted via /etc/modprobe.d/i2c-i801.conf.
Since Yocto treats it as a configuration file, it gets backed up when upgrading, which can break the system when going back from main/nightly to a previous release.
To avoid this happening, explicitly drop the file from backups.
=> base-files: do not backup /etc/modprobe.d/i2c-i801.conf

recipes-core/images/full.bb
Both kernel-module-linux-kernel-bde and kernel-module-linux-user-bde are pulled in by the ofdpa package already. There is no need to have them in BISDN_SWITCH_IMAGE_EXTRA_INSTALL.
=> images: full: remove redundant bde kernel modules

recipes-support/mstpd/mstpd_0.1.0.bb
Since we are basing our build on the 0.1.0 release and not a random git commit, let the recipe reflect that, and append our own version to `PV` instead.
While doing that, use that PV as the branch name, as we name our branches after them.
=> mstpd: use upstream version in recipe

conf/machine/accton-csp7551.conf, recipes-core/platform-onl-init/files/platform-x86-64-accton-csp7551-r0-init.sh, recipes-core/platform-onl-init/platform-onl-init_%.bbappend, recipes-kernel/accton-csp7551-mods/accton-csp7551-mods.bb, recipes-kernel/accton-csp7551-mods/files/0001-accton-csp7551-sfp-update-for-Linux-6.1.patch, recipes-kernel/accton-csp7551-mods/files/0002-accton-csp7551-cpld-update-for-Linux-6.1.patch, recipes-kernel/accton-csp7551-mods/files/COPYING, recipes-kernel/accton-csp7551-mods/files/Makefile, recipes-kernel/accton-csp7551-mods/files/accton_i2c_cpld.c, recipes-kernel/accton-csp7551-mods/files/fpga_driver.c, recipes-kernel/accton-csp7551-mods/files/x86-64-accton-csp7551-sfp.c, scripts/installer/install.sh, scripts/installer/machine/x86_64-accton_csp7551-r0/platform.conf
This PR adds code and configuration specific to the Accton CSP7551. Most notably, it adds platform drivers (cpld, sfp, fpga). It also contains a platform initialization script, creates configuration files for the network ports giving the CPU access to the Tofino chip, and increases the partition created for BISDN Linux from 6 GB to 160 GB.
=> Add support for Accton CSP7551

recipes-protocols/frr/files/CVE-2022-36440.patch, recipes-protocols/frr/files/CVE-2022-40318.patch, recipes-protocols/frr/files/CVE-2022-43681.patch, recipes-protocols/frr/frr_8.2.2.bbappend
Fix frr CVEs CVE-2022-36440, CVE-2022-40318, CVE-2022-43681 locally until the fixes get merged at OE upstream.
Reference: https://github.com/openembedded/meta-openembedded/pull/688
=> frr: fix CVEs CVE-2022-36440, CVE-2022-40318, CVE-2022-43681

recipes-extended/onie-tools/onie-tools/onie-bisdn-upgrade
According to the ONIE Design specification[1], kernel arguments for ONIE are supposed to be passed via the U-Boot environment variable 'onie_debugargs', so let's do that instead of relying on U-Boot not quoting variables.
[1] https://opencomputeproject.github.io/onie/design-spec/uboot_nos_interface.html#u-boot-platform-adding-kernel-command-arguments
Fixes: 1e27d475ea45 ("onie-tools: add support for u-boot-arch based devices")
=> onie-tools: user proper interface on u-boot for kernel arguments

recipes-support/libnl/libnl/0005-bridge-vlan-add-per-vlan-stp-state-object-and-cache.patch, recipes-support/libnl/libnl_3.7.0.bb
When parsing a RTM_VLAN* message, we need to make sure to properly account for the header, else our reminder may be too large as it does not account for the alignment, causing us to read beyond the message.
This then may lead to a crash if the message ends on a page boundary, and the following page is unmapped.
Fixes: d2755c742a1e ("libnl: bridge-vlan-db: add support for bridge-vlan notifications")
=> libnl: bridge_vlan: properly account for the bridge_vlan header

recipes-support/mstpd/mstpd_0.1.0.bb
Since we skip the header, we also need to substract it from the data length, else we will read beyond the bridge vlan message.
Fixes: 9d1f4bb92dcb ("mstpd: replace naive driver_dep with proper per vlan state setting")
=> mstpd: do not try to read beyond the end of vlan messages

recipes-extended/onie-tools/onie-tools/onie-bisdn-upgrade
Using a static IP configuration is mostly useless, as ONIE does not support specifying a gateway or a DNS server, so this only works if the server used for retrieving the image from is on the same subnet.
Additionally, the script does no parameter validation, so using e.g.
> $ onie-bisdn-upgrade \<url\> -y
would make it set "-y" as the IP address, which will then cause ONIE to configure an IP address interpreting that as an address.
To make matters worse, this configuration is sticky, and ONIE will be stuck with this misconfiguration until the next successful installation, or being manually reconfigured via serial.
So instead of trying to fix up a barely usable thing, let's drop the support for it and always use DHCP (the default).
=> onie-tools: onie-bisdn-upgrade: drop ip configuration support

recipes-devtools/python/python3-ryu_git.bb
Add the correct CVE_PRODUCT name so cve check can scan for vulnerabilites.
=> python3-ryu: add CVE_PRODUCT for CVE reporting

recipes-extended/packagegroups/packagegroup-bisdn-linux-extra.bb
To allow easily building and maintaining a list of packages to provide for releases, create a packagegroup that will depend on all packages that we want to provide as downloadable packages.
For now just define a single packagegroup to be targeted as an extra package to be build, which in turn (r)depends on all packages we want to provide as extra packages.
=> add a packagegroup for defining downloadable packages

conf/machine/accton-csp7551.conf, recipes-core/images/minimal.bb
Now that the machines depend on onl themselves, there is no need to explicitly include it anymore.
=> drop explicit onl package include from image

recipes-extended/packagegroups/packagegroup-bisdn-linux-extra.bb
Add useful packages that are currently installed with the Accton CSP7551 image to the list of packages that are built as optional downloads for all platforms.
Keep them in the CSP7551 image at least for now -- removing them will require tweaks to downstream processes.
=> packagegroup-bisdn-linux-extra: add packages from CSP7551

recipes-protocols/frr/frr/CVE-2023-46752.patch, recipes-protocols/frr/frr/CVE-2023-46753.patch, recipes-protocols/frr/frr/CVE-2023-47234.patch, recipes-protocols/frr/frr/CVE-2023-47235.patch, recipes-protocols/frr/frr_9.0.1.bb, recipes-protocols/frr/frr_9.0.1.bbappend
Add patches fixing CVE CVE-2023-46752, CVE-2023-46753, CVE-2023-47234, and CVE-2023-47235 to FRR 9.0.
Patch order is commit order, not CVE numerical order, to avoid fuzz / need for rebasing of the patches.
References:
https://nvd.nist.gov/vuln/detail/CVE-2023-46752
https://nvd.nist.gov/vuln/detail/CVE-2023-46753
https://nvd.nist.gov/vuln/detail/CVE-2023-47234
https://nvd.nist.gov/vuln/detail/CVE-2023-47235
Based on https://patchwork.yoctoproject.org/project/oe/patch/20231122093934.117102-1-jonas.gorski@bisdn.de/
=> frr: fix CVEs CVE-2023-4675{2,3} and CVE-2023-4723{4,5}

recipes-core/base-files/base-files/system-backup.txt, recipes-core/feed-config/b-isdn-feed-config-opkg_1.0.bb
bisdn-feed-config-opkg marks /etc/opkg/base-feeds.conf and /etc/opkg/arch.conf as configuration files, which we then later prevent from being backed up via system-backup.txt.
So let's just not mark them as configuration files, then we don't need to remove them from the backup later.
=> bisdn-feed-config-opkg: do not mark files as CONFFILES

recipes-core/base-files/base-files/system-backup.txt
This PR add a few additional entries to the list of files that are backed up and restored during an operating system upgrade: /etc/hostname, /etc/hosts, and the ssh host keys.
=> base-files: back up additional files

scripts/installer/machine/arm-accton_as4610_30-r0/platform.conf
Currently the installer relies on our default fallback fit configuration is also the default configuration of the fit image. This just happens to be identical, and may change in the future, so be explicit about which configuration is our fallback configuration for AS4610.
=> installer: accton-as4610: use explicit default fit configuration

recipes-extended/ofdpa-tools/ofdpa-tools/switch_tcpdump
This PR contains several changes to the switch_tcpdump script which should now be easier to use, more robust, and more powerful while retaining backward compatibility.
Changes:
- avoid leaving ACL table rules after user interruption
- allow passing additional options to tcpdump
- make output to stdout the default (do no require `--stdout` argument)
- add examples to help message
- reduce noise in console messages
=> switch_tcpdump update

scripts/installer/machine/arm-accton_as4610_30-r0/platform.conf
Since 15d96e67675a ("onie-tools: user proper interface on u-boot for kernel arguments") we use the proper variable, and onie_boot_reason contains a single word without spaces. So there is no need to fixup the boot_diag command anymore to handle spaces.
Tested via:
1. uninstall current image (which will reset the U-Boot environment)
2. install image with the change applied
3. run `onie-nos-install` to re-install the image
=> installer: accton-as4610: drop fixup for boot_diag command

recipes-support/libnl/libnl/0001-link-bonding-parse-and-expose-bonding-options.patch, recipes-support/libnl/libnl/0002-WIP-add-info-slave-data-support.patch, recipes-support/libnl/libnl/0003-link-bonding-expose-state-on-enslaved-interfaces.patch, recipes-support/libnl/libnl/0004-bridge-vlan-add-per-vlan-stp-state-object-and-cache.patch, recipes-support/libnl/libnl/0005-route-route_obj-treat-each-IPv6-link-local-route-as-.patch, recipes-support/libnl/libnl/0006-link-ignore-incomplete-bridge-updates.patch, recipes-support/libnl/libnl_3.8.0.bb
For currently unknown reasons, the kernel sends a minimal RTM_NEWLINK message for a bridge shortly after attaching a port:
```
-- Debug: Received Message:
--------------------------   BEGIN NETLINK MESSAGE ---------------------------
[NETLINK HEADER] 16 octets
.nlmsg_len = 96
.type = 16 <route/link::new>
.flags = 0 <>
.seq = 0
.port = 0
[PAYLOAD] 16 octets
07 00 01 00 40 00 00 00 03 10 00 00 00 00 00 00 ....@...........
[ATTR 03] 9 octets
73 77 62 72 69 64 67 65 00                      swbridge.
[PADDING] 3 octets
00 00 00                                        ...
[ATTR 10] 4 octets
40 00 00 00                                     @...
[ATTR 04] 4 octets
dc 05 00 00                                     ....
[ATTR 16] 1 octets
02                                              .
[PADDING] 3 …
```
=> libnl: ignore incomplete bridge updates

recipes-extended/man-pages/files/switch_tcpdump.8, recipes-extended/man-pages/man-pages_%.bbappend, recipes-extended/ofdpa-tools/ofdpa-tools/switch_tcpdump
This PR contains a number of changes for switch_tcpdump that should make the script more robust and more user-friendly.
In particular, a custom signal handler increases the chance that we manage to remove the ACL rule correctly even when getting SIGINT or SIGTERM in quick succession. The script can now also deal automatically with an existing ACL rule (e.g., left by a previous switch_tcpdump terminated by SIGKILL) instead of passing on the error message from ofda_acl_flow_cli.py.
The documentation has also been updated and extended.
=> Make switch_tcpdump more robust and user-friendly

recipes-extended/man-pages/files/onie-bisdn-upgrade.1, recipes-extended/onie-tools/onie-tools/onie-bisdn-upgrade
Update man page for onie-bisdn-upgrade:
- drop description of IMAGEURL option which has been removed
- make title like look more like a "standard" man page
- tweak description in name section
- avoid justified text with long URL, it ends up looking something like
"URL    of   an   installable   BISDN   Linux   image   (example:"
- move usage example to new examples section
- replace sample URLs with ones that look more like our current repo URLs
Update onie-bisdn-upgrade script:
- replace sample URLs with ones that look more like our current repo URLs
- slight reformatting of examples
=> Update onie-bisdn-upgrade documentation

recipes-extended/man-pages/files/onie-bisdn-upgrade.1, recipes-extended/onie-tools/onie-tools/onie-bisdn-upgrade
When run without -d, onie-bisdn-upgrade offers this warning:
`Upgrading BISDN Linux to install-source: <URL> using Client-IP-cfg: dhcp! Please confirm system reboot: [y/N]`
The reboot should be rather obvious when installing a new operating system. However, upgrading BISDN Linux will preserve files only if they are listed in `/var/lib/opkg/info/*.conffiles` or
`/etc/default/{system,user}-backup.txt`. [1]
This change updates the script and its man page to warn prominently about the potential loss of files the user may want to keep.
[1] https://docs.bisdn.de/getting_started/install_bisdn_linux.html#backup-filesfolders-across-installations
=> Update onie-bisdn-upgrade documentation to warn about file loss

conf/distro/bisdn-linux.conf
Cleanup and update distro features to match more what devices we target:
- disable pulseaudio support (no audio)
- disable wayland, vulkan, opengl (no video)
- disable pcmcia (we're not that ancient)
- disable usb gadget (we're not that embedded)
- enable vfat (mostly enables mkfs.vfat)
No substantial changes in the image, just a clean up.
=> cleanup and update distro features

recipes-support/libnl/libnl/0001-cache-fix-new-object-in-callback-v2-on-updated-objec.patch, recipes-support/libnl/libnl/0002-route-fix-IPv6-ecmp-route-deleted-nexthop-matching.patch, recipes-support/libnl/libnl/0003-nexthop-add-a-identical-helper-function.patch, recipes-support/libnl/libnl/0004-route-use-the-new-helper-function-for-comparing-next.patch, recipes-support/libnl/libnl/0005-link-bonding-parse-and-expose-bonding-options.patch, recipes-support/libnl/libnl/0006-WIP-add-info-slave-data-support.patch, recipes-support/libnl/libnl/0007-link-bonding-expose-state-on-enslaved-interfaces.patch, recipes-support/libnl/libnl/0008-bridge-vlan-add-per-vlan-stp-state-object-and-cache.patch, recipes-support/libnl/libnl/0009-route-route_obj-treat-each-IPv6-link-local-route-as-.patch, recipes-support/libnl/libnl/0010-link-ignore-incomplete-bridge-updates.patch, recipes-support/libnl/libnl_3.8.0.bb
Backport the fix for updated object notifications, where the update was accidentially set to the update, not the updated object.
This fixes incomplete ecmp route update notifications.
=> libnl: backport fix for updated object notifications

recipes-support/libnl/libnl/0006-WIP-add-info-slave-data-support.patch, recipes-support/libnl/libnl/0007-link-bonding-expose-state-on-enslaved-interfaces.patch, recipes-support/libnl/libnl/0008-bridge-vlan-add-per-vlan-stp-state-object-and-cache.patch, recipes-support/libnl/libnl/0009-route-route_obj-treat-each-IPv6-link-local-route-as-.patch, recipes-support/libnl/libnl/0010-link-ignore-incomplete-bridge-updates.patch, recipes-support/libnl/libnl_3.8.0.bb
Fix cloning links with slave ops. This fixes a crash when trying to clone a link with slave ops but not standard link ops, and now properly propagates the ops, as well as ups the reference.
Fixes: d116d6d8bba5 ("libnl: add slave data support")
=> libnl: fix cloning links with slave ops

scripts/installer/install.sh
Add support for creating a default network config during installation.
By setting the environment variable BISDN_DEFAULT_CONFIG, the identically named example configuration shipped by the baseboxd package will be installed.
This will disable the take over of any configuration from a previous installation, to avoid configuration conflicts.
As a special keyword, 'none' is accepted as a way to prevent configuration backup without creating a default configuration.
=> installer: add support for default configurations

scripts/installer/install.sh
The step that takes longer than any other step of the install process should have a presence in the log file. With this change, the user will no longer wonder what the installer is doing for what can be almost 3 minutes on slower platforms.
With the change, the log will look something like this:
```
Writing superblocks and filesystem accounting information: done
Writing root file system: done
Success: Support tarball created: /tmp/tmp.wzusn1/onie-support.tar.bz2
```
=> installer: indicate when rootfs is getting written

scripts/installer/install.sh
Other distros use /usr/share/doc, there is no reason for us to use /usr/share/docs.
=> Fix /usr/share/doc path

recipes-support/libnl/libnl/0001-cache-fix-new-object-in-callback-v2-on-updated-objec.patch, recipes-support/libnl/libnl/0002-route-fix-IPv6-ecmp-route-deleted-nexthop-matching.patch, recipes-support/libnl/libnl/0003-nexthop-add-a-identical-helper-function.patch, recipes-support/libnl/libnl/0004-route-use-the-new-helper-function-for-comparing-next.patch, recipes-support/libnl/libnl/0005-link-bonding-parse-and-expose-bonding-options.patch, recipes-support/libnl/libnl/0006-WIP-add-info-slave-data-support.patch, recipes-support/libnl/libnl/0007-link-bonding-expose-state-on-enslaved-interfaces.patch, recipes-support/libnl/libnl/0008-bridge-vlan-add-per-vlan-stp-state-object-and-cache.patch, recipes-support/libnl/libnl/0009-route-route_obj-treat-each-IPv6-link-local-route-as-.patch, recipes-support/libnl/libnl/0010-link-ignore-incomplete-bridge-updates.patch, recipes-support/libnl/libnl_3.9.0.bb
Update to libnl 3.9, which is mostly a bug fix release.
Most relevant change is that there was some bond link support added, so rebase our extension on top of it.
Full changelog:
bdf83151326e libnl-3.9.0 release
aa7353fde853 include/linux-private: import 'seg6 local' headers from kernel tree
9466f680a58c lib: remove unused assignment in nl_addr_parse()
acd05d6e8066 route/tc: avoid integer overflow in rtnl_tc_calc_cell_log()
daa8efcb4c45 xfrm: return -NLE_MISSING_ATTR from xfrmnl_sa_get_auth_params()
d8a1ff30c486 xfrm: fix leaking usertemplate in xfrmnl_sp_parse()
4fcb075720ed socket: workaround coverity warning about time_t handling
f743c62fa69e github: update Fedora image and version for clang-format
f33e8cd68344 clang-format: rework container script
aea3f9f2d8b6 lib: fix signed overflow …
=> libnl: update to 3.9.0

conf/distro/bisdn-linux.conf, recipes-core/images/full.bb
Enable the doc-pkgs image feature to automatically install man pages for
any package included in the image.
Increases the image size by about 11 MiB.
=> include man pages for all components in full images

recipes-connectivity/openssh/openssh/CVE-2024-6387.patch, recipes-connectivity/openssh/openssh_8.9p1.bbappend
sshd(8) in Portable OpenSSH versions 8.5p1 to 9.7p1 (inclusive). Race condition resulting in potential remote code execution. A race condition in sshd(8) could allow remote code execution as root on non-OpenBSD systems. This attack could be prevented by disabling the login grace timeout (LoginGraceTime=0 in sshd_config) though this makes denial-of service against sshd(8) considerably easier. For more information, please refer to the release notes [1] and the report from the Qualys Security Advisory Team [2] who discovered the bug.
[1] https://www.openssh.com/txt/release-9.8
[2] https://www.qualys.com/2024/07/01/cve-2024-6387/regresshion.txt
References:
https://www.openssh.com/security.html
[jonas.gorski: convert to bbappend]
=> openssh: fix CVE-2024-6387

recipes-core/images/onie-nos-installer.inc
SSTATE_SKIP_CREATION also needs the new override syntax, but was missed when updating the layer for kirkstone.
Should silence spurious warnings about changing sstate hashes on subsequent image builds with the same source tree.
Fixes: c3425e295236 ("update layer to kirkstone")
=> onie-nos-installer: fix sstate skip override syntax

recipes-extended/ofdpa-tools/ofdpa-tools/switch_tcpdump
Once we have decided to terminate the tcpdump subprocess, we should break out of the loop instead of staying and trying to terminate the process until it is gone.
This should fix switch_tcpdump sometimes showing multiple "Reached capture timeout, stopping" messages in a row.
=> switch_tcpdump: break out of loop after terminating tcpdump

conf/templates/bisdn-linux/bblayers.conf.sample, conf/templates/bisdn-linux/local.conf.sample
Import local.conf.sample and bblayers.conf.sample from the bisdn-linux
repository to allow using this layer as a template configuration source.
This will only be needed for scarthgap, but it also works with
kirkstone, so no reason to not do it here as well.
=>  conf: import template configuration from bisdn-linux

recipes-extended/ofdpa-tools/ofdpa-tools/switch_tcpdump
If switch_tcpdump terminates the tcpdump process (for instance, because
the timeout has been reached), then the returncode of the subprocess may
be -15, the negative value of SIGTERM (it is racy, but it does happen).
That is not an error we want to pass on as the exit status for
switch_tcpdump, so in that case, set the exit status to 0.
=> switch_tcpdump: handle SIGTERM signal indication

recipes-protocols/frr/frr/0001-CVE-2024-44070.patch, recipes-protocols/frr/frr_9.0.3.bb
Fix CVE-2024-44070 by cherry-picking the upstream fix.
ref: https://nvd.nist.gov/vuln/detail/CVE-2024-44070
=> frr: fix CVE-2024-44070

recipes-extended/baseboxd-tools/baseboxd-tools/bundle-debug-info
FRR will create named nexthops for all routes, so we should collect all active nexthops as well.
=> baseboxd-tools: also collect nexthop info in debug bundle

recipes-extended/baseboxd-tools/baseboxd-tools/bundle-debug-info
Depending on the host system, systemctl may reside in /bin or /usr/bin, so instead of hardcoding the path detect it at run time.
Fixes collecting mstpd state on servers.
Fixes: d86e4da81ea8 ("baseboxd-tools: bundle MSTPD state as well in collect-debug-info")
=> baseboxd-tools: bundle-debug-info: handle dynamic systemctl path

recipes-support/mstpd/mstpd_0.1.0.bb
Update mstpd to fix path cost calculation for link speeds > 65G.
=> mstpd: fix path cost calculation for link speeds > 65G

recipes-protocols/frr/frr_9.0.4.bbappend
Without libcap privilege is attained per process instead of per thread. Apart from being slow due to the need for synchronization [1], it is even broken as it does not guard unprivileged executions from being run in privileged context [2].
Fix this by always enabling libcap.
[1] https://github.com/FRRouting/frr/commit/7bfe765ae06fcc0a5570fdd793237e5fa828f7e7
[2] https://github.com/FRRouting/frr/issues/16747
=> frr: enable capabilities to fix racy unprivileged executions

recipes-support/mstpd/mstpd_0.1.0.bb
The 0.1.0+bisdn6 branch missed the version bump, so the binary still reported as 0.1.0+bisdn5. Fix this by moving to the correct commit.
Fixes: a9d0100212fe ("mstpd: fix path cost calculation for link speeds > 65G")
=> mstpd: correctly reported version as 0.1.0+bisdn6

recipes-extended/baseboxd/baseboxd_2.2.5.bb
Since baseboxd 2.2.1 we install the service file at the expected location, so we do not need to manually copy it anymore.
No changes in generated package:
$ sha256sum before/* after/*
10ef217e5bff25e0d3ea8affee2c2e9a6f61b68ff1c6d5b405694541773e090f  before/baseboxd_2.2.5-r0_corei7-64.ipk
10ef217e5bff25e0d3ea8affee2c2e9a6f61b68ff1c6d5b405694541773e090f  after/baseboxd_2.2.5-r0_corei7-64.ipk
=> baseboxd: drop service file location fixup

conf/distro/bisdn-linux.conf, files/group, files/passwd, recipes-core/systemd/systemd.inc
By default user ids and group ids are dynamically allocation on addition to the system. This isn't an issue for a fresh installation, but on upgrade, the run-preinsts service on first boot will add any missing users and groups that weren't present in the taken over passwd/group files.
These then might get assigned different ids than the one of the image, which then can cause a mismatch for ownership of supplied files and directories in the image.
Especially systemd's wheel group will take the lowest id in the 900s, which can change when adding new services with new users and groups to the image.
To fix that, enable the "useradd-staticids" USERADDEXTENSION, where Yocto will use ids from files/{passwd,groups} when adding users via USERADD:*, and make it fatal if a user or group does not …
=> distro: enable static group ids and user ids

recipes-devtools/run-preinsts/run-preinsts/run-preinsts.service
systemd-tmpfiles-setup may attempt to create files or directories for new services with new users, but these users may not yet exist on first boot after an upgrade, since only run-preinsts creates them.
So move the run-preinsts to before systemd-tmpfiles-setup to ensure any referenced users and groups are added and defined.
=> run-preinsts: run before systemd-tmpfiles-setup

conf/distro/bisdn-linux.conf, recipes-extended/baseboxd/baseboxd.inc, recipes-support/rofl-common/rofl-common.inc, recipes-support/rofl-ofdpa/rofl-ofdpa.inc
Update branch references as appropriate:
* baseboxd: use 1.x
* rofl-*: use main for now
* distro/FEEDURIPREFIX: use v4.x (the bisdn-linux branch for v4.x)
=> v4.x: update branch references as appropriate

recipes-extended/packagegroups/packagegroup-bisdn-linux-extra.bb
Valgrind is a useful utility to debug memory issues (leaks, use-after-free, etc), so add it to the debugging extra set.
=> packagegroup-bisdn-linux-extra: add valgrind

recipes-core/images/full.bb
We make use of the python3 docker module in our testing, so we should just include it instead of installing later.
=> full: include python3-docker

recipes-extended/baseboxd/baseboxd_1.12.9.bb
Update baseboxd to 1.12.9 to fix failures for sometimes missing VLAN groups.
=> v4.x: baseboxd: update to 1.12.9

conf/distro/bisdn-linux.conf, recipes-core/images/full.bb
Code wise docker-ce is identical to docker-moby, the only difference is the package name and version:
SRCREV_docker = "791d8ab87747169b4cbfcdf2fd57c81952bae6d5"
DOCKER_VERSION = "20.10.25-ce"
vs
SRCREV_moby = "791d8ab87747169b4cbfcdf2fd57c81952bae6d5"
DOCKER_VERSION = "20.10.25"
newer Yocto versions therefore dropped the docker-ce package, so we should also not use it anymore. So let's switch docker to the "new" package.
=> full: replace docker-ce with docker-moby

conf/distro/bisdn-linux.conf
We can't just replace docker-ce with docker-moby, we also need to override the preferred provider to make the change effective.
Fixes the following build error:
```
ERROR: Nothing RPROVIDES 'docker-moby' (but meta-bisdn-linux/recipes-core/images/full.bb RDEPENDS on or otherwise requires it)
docker-moby was skipped: PREFERRED_PROVIDER_virtual/docker set to docker-ce, not docker-moby
ERROR: Required build target 'full' has no buildable providers.
```
Fixes: 12eda9946056 ("full: replace docker-ce with docker-moby")
=> distro: set PREFERRED_PROVIDER for docker to docker-moby

scripts/installer/lib/backup.sh
Add support for backing up and restoring explicitly disabled and enabled
services by checking their symlinks and restoring or removing them when
applying the backup.
It does naive enabled/disabled services heuristic:
- if the .preset does not say enabled, and there is a symlink in
multi-user.target.wants, recreate the symink on restore
- if the .preset says enabled, and there was no symlink in
multi-user.target.wants, remove the symlink on restore
Additionally, it only checks certain services:
- Skip any oneshot services (these are expected to be disabled with
enabled preset after first boot)
- Skip any services not targeting multi-user
It does support parameterized services though, as supported by frr (via
frr@something).
This allows e.g. docker to continue to be enabled after an update …
=> installer: add a naive systemd service state backup and restore

recipes-connectivity/iproute2/iproute2_6.7.0.bb
Backport newer iproute2 from scarthgap[1], as kirkstone's 5.17 does not
know locked ports or locked fdb entries yet. This more closely matches
with our used kernel 6.6 and its feature set.
[1] https://github.com/openembedded/openembedded-core/blob/scarthgap/meta/recipes-connectivity/iproute2/iproute2_6.7.0.bb
=> iproute2: backport iproute2 6.7 from scarthgap

recipes-support/libnl/libnl/0001-cache-cache_include-fix-double-put-for-cloned-object.patch, recipes-support/libnl/libnl/0002-route-add-missing-rtnl_nh_get_oif-symbol.patch, recipes-support/libnl/libnl/0003-cache-add-nl_cache_resync_v2.patch, recipes-support/libnl/libnl/0004-link-bonding-add-primary-getters-and-setters.patch, recipes-support/libnl/libnl/0005-WIP-add-info-slave-data-support.patch, recipes-support/libnl/libnl/0006-link-bonding-expose-state-on-enslaved-interfaces.patch, recipes-support/libnl/libnl/0007-bridge-vlan-add-per-vlan-stp-state-object-and-cache.patch, recipes-support/libnl/libnl/0008-route-route_obj-treat-each-IPv6-link-local-route-as-.patch, recipes-support/libnl/libnl/0009-link-ignore-incomplete-bridge-updates.patch, recipes-support/libnl/libnl_3.11.0.bb
Import two changes from upstream from us:
* fix a missing export of rtnl_nl_get_oif()
* add the missing nl_cache_resync_v2() variant
while at it, reorder the patches so that backports come first, for easier updating/rebasing.
=> libnl: import latest updates from upstream

recipes-support/mstpd/mstpd_0.1.0.bb
Instead of hardcoding /sbin as the sbindir, use ${base_sbindir} for it. This variable will properly follow usrmerge if enabled.
Installing to /usr/sbin in this case is harmless, as /sbin will be symlink to /usr/sbin, so any /sbin/* calls will continue to work.
=> mstpd: use ${base_sbindir} instead of hardcoding /sbin

recipes-extended/baseboxd/baseboxd_2.3.0.bb
Update baseboxd to 2.3.0:
```
ec5fba861b9f Bump version to 2.3.0
1e28461b5fea Merge pull request #457 from bisdn/jogo_port_locked dcab584f6930 cnetlink: ignore locked fdb entries as well 3b3a65e3ccca cnetlink: properly handle ll neigh handable changes a299dd3ee313 nl_bridge: handle port locked
824632b855fc nbi_impl: initialize learning on connect 87b00ee6b64e ofdpa_client: expose per port learning configuration ad2568013a95 proto: update with OF-DPA port learn functions 244e8384fc0d Bump version to 2.2.6
73f69dc02417 Merge pull request #454 from bisdn/jogo_fix_tap_buffer_overrun 3e7e0378baeb tap_io::handle_read_event(): fix potential buffer overrun
```
=> baseboxd: update to 2.3.0

recipes-core/systemd/files/0001-basic-linux-update-linux-uapi-headers.patch, recipes-core/systemd/files/0001-network-bridge-add-support-for-NO_LL_LEARN.patch, recipes-core/systemd/files/0001-partition-fix-build-with-newer-linux-btrfs.h-uapi-he.patch, recipes-core/systemd/files/0002-network-bridge-add-support-for-IFLA_BRPORT_LOCKED.patch, recipes-core/systemd/files/0003-network-bridge-add-support-for-IFLA_BRPORT_MAB.patch, recipes-core/systemd/systemd_250%.bbappend
Backport support for locked bridge ports from systemd 258 [1].
[1] https://github.com/systemd/systemd/pull/36150
=> systemd: add support for locking ports

recipes-extended/baseboxd/baseboxd_2.3.1.bb
Update baseboxd to 2.3.1:
* a8c91ae4dfeb Bump version to 2.3.1
* 7737d7489ccd Merge pull request #460 from bisdn/jogo_fix_l2_move_learn
* 7170e72d94ff netlink: setup port learning from with the netlink thread
* 00ed2ca2f4a0 controller: fix setting station move configuration
=> baseboxd: update to 2.3.1

recipes-connectivity/hostapd/files/0001-Split-ap_sta_set_authorized-into-two-steps.patch, recipes-connectivity/hostapd/files/0002-netlink-allow-listening-for-neighbor-events.patch, recipes-connectivity/hostapd/files/0003-add-wired-driver-extra-options.patch, recipes-connectivity/hostapd/files/0004-import-base-MAB-handling-code-from-Cumulus.patch, recipes-connectivity/hostapd/files/0005-use-a-timer-for-mab-instead-of-forcing-drivers-to-se.patch, recipes-connectivity/hostapd/files/0006-drivers-add-a-linux-wired-driver.patch, recipes-connectivity/hostapd/files/0007-driver_linux_wired-handle-neighs-going-away.patch, recipes-connectivity/hostapd/files/0008-driver_wired_linux-flush-all-entries-on-start-stop.patch, recipes-connectivity/hostapd/files/0009-driver_wired_linux-wait-for-bridge-attachment.patch, recipes-connectivity/hostapd/hostapd_2.10.bbappend
Fix two issues found in internal testing for the wired driver:
1. flush fdb entries on startup and stop
This ensures that no unlocked fdb entries remain after stop, or any previous unlocked entries may unexpectedly allow traffic on startup.
2. wait for bridge attachement on statup
Setting ports to locked only works when attached to a bridge, but on boot startup of hostapd runs in parallel with systemd-networkd, so the port may not be attached to the bridge yet. So wait for the bridge in case the port isn't attached yet.
Fixes: 2ced4ac52570 ("hostapd: add PoC handler for locked ports")
=> hostapd: add two fixes for 802.1x wired driver

recipes-extended/baseboxd-tools/baseboxd-tools/bundle-debug-info
Now that we may set extended bridge port parameters only visible in detailed link output (locked and mab), also collect the appropriate output.
=> baseboxd-tools: get detailed link info in debug-info

recipes-extended/baseboxd/baseboxd_1.13.0.bb
Update baseboxd to 1.13.0:
```
95b7c6c65a3e Bump version to 1.13.0
04eb09a8bdd8 Merge pull request #461 from bisdn/jogo_1.x_port_locked
170617c7532c netlink: setup port learning from with the netlink thread
e86a05ef205a controller: fix setting station move configuration
db31e63bdf88 cnetlink: ignore locked fdb entries as well
1dee72dcfc0d cnetlink: properly handle ll neigh handable changes
f13771037958 nl_bridge: handle port locked
81ba2cf045c6 nbi_impl: initialize learning on connect
c667727cf6f4 ofdpa_client: expose per port learning configuration
c2986f1f7eee proto: update with OF-DPA port learn functions
e1b3a00b8091 Merge pull request #464 from bisdn/jogo_1.x_makefilefixes
7a849105b389 Makefile: automatically sign version bumps
0f0a8c32f74a Makefile: make sure a VERSON bump commit …
```
=> v4.: baseboxd: update to 1.13.0

recipes-protocols/net-snmp/net-snmp/0001-unload_all_mibs-fix-memory-leak-by-freeing-tclist.patch, recipes-protocols/net-snmp/net-snmp_5.9.3.bbappend
net-snmp got a broken patch that does not apply, causing the build to break:
ERROR: net-snmp-5.9.3-r0 do_patch: Applying patch '0001-unload_all_mibs-fix-memory-leak-by-freeing-tclist.patch' on target directory '.../work/cortexa9-vfp-poky-linux-gnueabi/net-snmp/5.9.3-r0/net-snmp-5.9.3'
CmdError('quilt --quiltrc .../work/cortexa9-vfp-poky-linux-gnueabi/net-snmp/5.9.3-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-unload_all_mibs-fix-memory-leak-by-freeing-tclist.patch
patching file snmplib/parse.c
Hunk #1 FAILED at 28.
Hunk #2 succeeded at 4225 (offset 10 lines).
1 out of 2 hunks FAILED -- rejects in file snmplib/parse.c
Patch 0001-unload_all_mibs-fix-memory-leak-by-freeing-tclist.patch does not apply (enforce with -f)
stderr: ')
Fix this by providing our own …
=> net-snmp: replace borked patch to fix compilation

recipes-connectivity/hostapd/files/0001-Split-ap_sta_set_authorized-into-two-steps.patch, recipes-connectivity/hostapd/files/0002-netlink-allow-listening-for-neighbor-events.patch, recipes-connectivity/hostapd/files/0003-add-wired-driver-extra-options.patch, recipes-connectivity/hostapd/files/0004-import-base-MAB-handling-code-from-Cumulus.patch, recipes-connectivity/hostapd/files/0005-use-a-timer-for-mab-instead-of-forcing-drivers-to-se.patch, recipes-connectivity/hostapd/files/0006-drivers-add-a-linux-wired-driver.patch, recipes-connectivity/hostapd/files/0007-driver_linux_wired-handle-neighs-going-away.patch, recipes-connectivity/hostapd/files/0008-driver_wired_linux-flush-all-entries-on-start-stop.patch, recipes-connectivity/hostapd/files/0009-driver_wired_linux-wait-for-bridge-attachment.patch
When a client gets immediately disconnected again, hostapd stops any 802.1x and frees its state machine object, but the timeout for switching to MAB may still be active. If the timeout then triggers, it tries to free sta->eapol_sm->identity, which causes a NULL pointer access, since eapol_sm is NULL.
Fix this by also canceling any pending MAB fallback timeouts on stopping 802.1.x
Fixes: 475aaa7a8547 ("hostapd: improve 802.1x support")
=> hostapd: fix potential crash with MAB and disconnected clients

recipes-extended/baseboxd/baseboxd_2.4.0.bb, recipes-support/rofl-ofdpa/rofl-ofdpa_2.1.0.bb
Update baseboxd to 2.4.0 and rofl-ofdpa to 2.1.0 with the newly added support for encapsulating traffic on a bridge port with a stacked VLAN tag.
This supports adding a VLAN interface as a bridge member, encapsulating all traffic with a VLAN tag based on that VLAN interface.
=> add support for stacked vlans on bridge ports

recipes-extended/man-pages/files/switch_tcpdump.8, recipes-extended/man-pages/man-pages_%.bbappend, recipes-extended/ofdpa-tools/ofdpa-tools/switch_tcpdump
This PR contains the following changes (backported from main):
- 5899839 switch_tcpdump: use c_byte value, not object
- 0b32033 switch_tcpdump: handle SIGTERM signal indication
- fe16d49 switch_tcpdump: use ctypes to convert to int8
- 68f8c0a switch_tcpdump: break out of loop after terminating tcpdump
- f224da6 Add man page for switch_tcpdump(8)
- e0290d4 switch_tcpdump: update usage examples and usage description
- b271bf0 switch_tcpdump: add custom signal handler
- 51ac1e6 switch_tcpdump: deal with missing/present acl rules automatically
- 1406bc4 switch_tcpdump: capture output from ofdpa_acl_flow_cli
- 8bc6c5f switch_tcpdump: allow unlimited filesize
- e1d3612 switch_tcpdump: flush print output immediately
- 90a8d0d switch_tcpdump: change error exit code
- 88a6a14 switch_tcpdump: …
=> Backport switch_tcpdump changes

recipes-extended/baseboxd-tools/baseboxd-tools/bundle-debug-info
Backport latest change to bundle-debug-info so we properly collect data for newest features backported to 4.x as well.
Backports of:
* https://github.com/bisdn/meta-bisdn-linux/pull/145
* https://github.com/bisdn/meta-bisdn-linux/pull/146
* https://github.com/bisdn/meta-bisdn-linux/pull/242
* https://github.com/bisdn/meta-bisdn-linux/pull/245
* https://github.com/bisdn/meta-bisdn-linux/pull/290
=> v4.x: sync support bundle script with main

recipes-extended/baseboxd/baseboxd_1.14.0.bb, recipes-support/rofl-ofdpa/rofl-ofdpa_2.1.0.bb
Update baseboxd to 1.14.0 and rofl-ofdpa to 2.1.0 with the newly added support for encapsulating traffic on a bridge port with a stacked VLAN tag.
This supports adding a VLAN interface as a bridge member, encapsulating all traffic with a VLAN tag based on that VLAN interface.
=> v4.x: add support for stacked vlans on bridge ports

recipes-extended/baseboxd/baseboxd_2.4.0.bb
It looks like the link sync introduces several regressions, so go back to the previous, much more stable version. E.g. l3 neighbors may get marked as unroutable, and IPv6 routes may go missing after a link change.
This reverts commit 1316cfc198f31c71bbdd2a65125b06f3744483d8.
=> Revert "baseboxd: update to 2.4.1"

recipes-core/feed-config/b-isdn-feed-config-opkg_1.0.bb, recipes-devtools/opkg/opkg-arch-config_%.bbappend
When we removed the bisdn-feed-config-opkg CONFFILES section in 0ac329e44b81 ("bisdn-feed-config-opkg: do not mark files as CONFFILES"), we assumed that this is the only source for these files. But it turns out there is also the Yocto base package 'opkg-arch-config' installing this file marked as a configuration file.
This triggers a backup of the file, and thus a broken machine feed when going back to 4.x or earlier release.
Since the only file provided by 'opkg-arch-config' is identical to the one provided by bisdn-feed-config-opkg, let's just not provide one by us, and unmark the one from opkg-arch-config as config.
Fixes: 0ac329e44b81 ("bisdn-feed-config-opkg: do not mark files as CONFFILES")
=> prevent backup of /etc/opkg/arch.conf again

recipes-extended/baseboxd/baseboxd_2.4.2.bb
Update baseboxd to 2.4.2:
```
5f66228f2175 Bump version to 2.4.2
db2ba9c33bf7 Merge pull request #474 from bisdn/jogo_revert_sync_routes 
a313eb9b1366 Revert "cnetlink: sync route cache on linkdown events" 
85a0ecc47b5b Merge pull request #473 from bisdn/jogo_linter_settings 
7d9f4d6a512d linter: invert the push branch restrictions 
c6585c7cf1e2 linter: always lint pull requests
9f664e582004 linter.yml: change default branch from master to main
```
=> baseboxd: update to 2.4.2

recipes-bsp/lm_sensors/lmsensors_3.6.0.bbappend
Until kirkstone is patched, apply the fix locally for the recently introduced breakage from [1].
[1] https://patchwork.yoctoproject.org/project/oe/patch/20250424125034.73053-1-l.anderweit@phytec.de/
=> lmsensors: fix build without sensord

recipes-extended/baseboxd-tools/baseboxd-tools/bundle-debug-info
Now that we have working port counters with knet, let's include them in our debug bundle as well.
Counters will look like this:
```
14: port5: group afstats subgroup mpls
14: port5: group link
RX:  bytes packets errors dropped  missed   mcast
952      12      0       0       0       8
TX:  bytes packets errors dropped carrier collsns
1062      11      0       0       0       0
14: port5: group offload subgroup l3_stats off used off
14: port5: group offload subgroup hw_stats_info
l3_stats off used off
14: port5: group offload subgroup cpu_hit
RX:  bytes packets errors dropped  missed   mcast
952      12      0       0       0       0
TX:  bytes packets errors dropped carrier collsns
1062      11      0       0       0       0
14: port5: group xstats_slave subgroup bond suite 802.3ad
14: …
```
=> baseboxd-tools: bundle-debug-info: include port counters

recipes-core/base-files/base-files/system-backup.txt, recipes-core/images/full.bb
Add wireguard-tools package to image to allow using wireguard tunnels.
Since wireguard uses a directory for its configuration and configuration
files can only bet set as files, add /etc/wireguard to system-backup.txt
as well.
Depends on https://github.com/bisdn/meta-open-network-linux/pull/188
=> full: add wireguard-tools

recipes-extended/onie-tools/onie-tools/onie-bisdn-upgrade
The usage text for onie-bisdn-upgrade contains a sample URL that mixes x86-64 and armel paths. Fixed.
=> onie-tools: fix usage text for onie-bisdn-upgrade

recipes-extended/baseboxd/baseboxd_3.0.0.bb, recipes-support/rofl-ofdpa/rofl-ofdpa_2.2.0.bb
Update baseboxd to 3.0.0 and rofl-ofdpa to 2.2.0 to enable the use of Termination MAC flows instead of ACL flows for reserved multicast traffic.
Fixes https://github.com/bisdn/bisdn-linux/issues/155.
=> baseboxd: use Termination MAC instead of ACL flows for reserved multicast
